import type { AppProps } from "next/app";
import Head from "next/head";
import Layout from "../components/Layout/Layout";
import { wrapper } from "../store";

import "bootstrap/dist/css/bootstrap.css";
import "../styles/globals.css";

function MyApp({ Component, pageProps }: AppProps) {
    return (
        // suppressHydrationWarning
        <div>
            <Head>
                <title> WesternUnion//WU </title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
                <link rel='preconnect' href='https://fonts.googleapis.com' />
                <link
                    rel='preconnect'
                    href='https://fonts.gstatic.com'
                    crossorigin
                />
                <link
                    href='https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;1,100;1,200;1,300;1,400;1,500&display=swap'
                    rel='stylesheet'
                ></link>
                <script
                    src='https://code.jquery.com/jquery-3.2.1.slim.min.js'
                    integrity='sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN'
                    crossorigin='anonymous'
                ></script>
                <script
                    src='https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js'
                    integrity='sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q'
                    crossorigin='anonymous'
                ></script>
                <script
                    src='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js'
                    integrity='sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl'
                    crossorigin='anonymous'
                ></script>

                <link
                    rel='stylesheet'
                    href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'
                ></link>
            </Head>
            <Layout>
                <Component {...pageProps} />
            </Layout>
        </div>
    );
}

export default wrapper.withRedux(MyApp);
